
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/thierry/ROS2/ros_ws/install/tutos/bin/"
      - "/home/thierry/ROS2/ros_ws/install/tutos/sbin/"
      - "/home/thierry/ROS2/ros_ws/install/tutos/"
      - "/home/thierry/ROS2/ros_ws/install/tutorials_interfaces/bin/"
      - "/home/thierry/ROS2/ros_ws/install/tutorials_interfaces/sbin/"
      - "/home/thierry/ROS2/ros_ws/install/tutorials_interfaces/"
      - "/home/thierry/ROS2/ros_ws/install/roversim/bin/"
      - "/home/thierry/ROS2/ros_ws/install/roversim/sbin/"
      - "/home/thierry/ROS2/ros_ws/install/roversim/"
      - "/home/thierry/.local/lib/python3.8/site-packages/sumo/bin/"
      - "/home/thierry/ogre-1.12/bin/"
      - "/home/thierry/.pyenv/plugins/pyenv-virtualenv/shims/"
      - "/home/thierry/.pyenv/shims/"
      - "/home/thierry/.pyenv/bin/"
      - "/home/thierry/Documents/emsdk/"
      - "/home/thierry/Documents/emsdk/upstream/emscripten/"
      - "/opt/openfoam11/thirdparty/platforms/linux64Gcc/gperftools-svn/bin/"
      - "/opt/paraviewopenfoam510/bin/"
      - "/opt/openfoam11/bin/"
      - "/opt/openfoam11/wmake/"
      - "/home/thierry/OpenFOAM/thierry-11/platforms/linux64GccDPInt32Opt/bin/"
      - "/opt/site/11/platforms/linux64GccDPInt32Opt/bin/"
      - "/opt/openfoam11/platforms/linux64GccDPInt32Opt/bin/"
      - "/home/thierry/MiniConda/condabin/"
      - "/home/thierry/.nvm/versions/node/v22.11.0/bin/"
      - "/opt/ros/foxy/bin/"
      - "/home/thierry/.local/bin/"
      - "/home/thierry/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/snap/bin/"
      - "/usr/share/sumo/tools/"
    searched_directories:
      - "/home/thierry/ROS2/ros_ws/install/tutos/bin/uname"
      - "/home/thierry/ROS2/ros_ws/install/tutos/sbin/uname"
      - "/home/thierry/ROS2/ros_ws/install/tutos/uname"
      - "/home/thierry/ROS2/ros_ws/install/tutorials_interfaces/bin/uname"
      - "/home/thierry/ROS2/ros_ws/install/tutorials_interfaces/sbin/uname"
      - "/home/thierry/ROS2/ros_ws/install/tutorials_interfaces/uname"
      - "/home/thierry/ROS2/ros_ws/install/roversim/bin/uname"
      - "/home/thierry/ROS2/ros_ws/install/roversim/sbin/uname"
      - "/home/thierry/ROS2/ros_ws/install/roversim/uname"
      - "/home/thierry/.local/lib/python3.8/site-packages/sumo/bin/uname"
      - "/home/thierry/ogre-1.12/bin/uname"
      - "/home/thierry/.pyenv/plugins/pyenv-virtualenv/shims/uname"
      - "/home/thierry/.pyenv/shims/uname"
      - "/home/thierry/.pyenv/bin/uname"
      - "/home/thierry/Documents/emsdk/uname"
      - "/home/thierry/Documents/emsdk/upstream/emscripten/uname"
      - "/opt/openfoam11/thirdparty/platforms/linux64Gcc/gperftools-svn/bin/uname"
      - "/opt/paraviewopenfoam510/bin/uname"
      - "/opt/openfoam11/bin/uname"
      - "/opt/openfoam11/wmake/uname"
      - "/home/thierry/OpenFOAM/thierry-11/platforms/linux64GccDPInt32Opt/bin/uname"
      - "/opt/site/11/platforms/linux64GccDPInt32Opt/bin/uname"
      - "/opt/openfoam11/platforms/linux64GccDPInt32Opt/bin/uname"
      - "/home/thierry/MiniConda/condabin/uname"
      - "/home/thierry/.nvm/versions/node/v22.11.0/bin/uname"
      - "/opt/ros/foxy/bin/uname"
      - "/home/thierry/.local/bin/uname"
      - "/home/thierry/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{CMAKE_PREFIX_PATH}:
        - "/home/thierry/ROS2/ros_ws/install/tutos"
        - "/home/thierry/ROS2/ros_ws/install/tutorials_interfaces"
        - "/home/thierry/ROS2/ros_ws/install/roversim"
      ENV{PATH}:
        - "/home/thierry/.local/lib/python3.8/site-packages/sumo/bin"
        - "/home/thierry/ogre-1.12/bin"
        - "/home/thierry/.pyenv/plugins/pyenv-virtualenv/shims"
        - "/home/thierry/.pyenv/shims"
        - "/home/thierry/.pyenv/bin"
        - "/home/thierry/Documents/emsdk"
        - "/home/thierry/Documents/emsdk/upstream/emscripten"
        - "/opt/openfoam11/thirdparty/platforms/linux64Gcc/gperftools-svn/bin"
        - "/opt/paraviewopenfoam510/bin"
        - "/opt/openfoam11/bin"
        - "/opt/openfoam11/wmake"
        - "/home/thierry/OpenFOAM/thierry-11/platforms/linux64GccDPInt32Opt/bin"
        - "/opt/site/11/platforms/linux64GccDPInt32Opt/bin"
        - "/opt/openfoam11/platforms/linux64GccDPInt32Opt/bin"
        - "/home/thierry/MiniConda/condabin"
        - "/home/thierry/.nvm/versions/node/v22.11.0/bin"
        - "/opt/ros/foxy/bin"
        - "/home/thierry/.local/bin"
        - "/home/thierry/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
        - "/usr/share/sumo/tools"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-179-generic - x86_64
...
